/** @file

  Platform Configuration C Struct Header File.

  Copyright (c) 2024, Intel Corporation. All rights reserved.<BR>
  SPDX-License-Identifier: BSD-2-Clause-Patent

  This file is automatically generated. Please do NOT modify !!!

**/

#ifndef __CONFIG_DATA_COMMON_STRUCT_H__
#define __CONFIG_DATA_COMMON_STRUCT_H__

#pragma pack(1)



#define    CDATA_GEN_TAG                  0x010
#define    CDATA_PLDSEL_TAG               0x011
#define    CDATA_PLAT_NAME_TAG            0x070
#define    CDATA_CAPSULE_INFO_TAG         0x080



typedef struct {
  
  /* Pad Group */
  UINT32                      PadGroup : 8;
  
  /* Pin Number */
  UINT32                      PinNumber : 8;
  
  /* Enable GPIO Payload Selection when PayloadId is 'AUTO' */
  UINT32                      Enable : 1;
  
  /* Pin Polarity */
  UINT32                      PinPolarity : 1;
  
  /* Reserved */
  UINT32                      Rsvd1 : 14;

} PAYLOAD_SEL_GPIO_PIN;


typedef struct {
  
  /* Platform Name */
  UINT64                      PlatformName;

} PLAT_NAME_CFG_DATA;


typedef struct {
  
  /* Debug Print Level */
  UINT32                      DebugPrintLevel;
  
  /* Payload ID */
  UINT32                      PayloadId;
  
  /* OS Crash Memory Size */
  UINT8                       OsCrashMemorySize;
  
  /* Enable Crash Mode */
  UINT8                       EnableCrashMode;
  
  /* RpmbKeyProvisioning */
  UINT8                       RpmbKeyProvisioning;
  
  /* Platform VBT table */
  UINT32                      VbtImageId;
  
  /* Current Boot Option */
  UINT8                       CurrentBoot;
  
  /* Boot to OsLoader shell */
  UINT8                       BootToShell;
  
  /* N/A */
  UINT8                       Dummy[3];

} GEN_CFG_DATA;


typedef struct {
  
  /* N/A */
  PAYLOAD_SEL_GPIO_PIN        PldSelGpio;

} PLDSEL_CFG_DATA;


typedef struct {
  
  /* DevType */
  UINT8                       DevType;
  
  /* Boot Device instance */
  UINT8                       DevInstance;
  
  /* N/A */
  UINT8                       Reserved[3];
  
  /* Hardware Partition */
  UINT8                       HwPart;
  
  /* Software Partition */
  UINT8                       SwPart;
  
  /* File System Type */
  UINT8                       FsType;
  
  /* Capsule File Name */
  UINT8                       FileName[16];
  
  /* LBA address for capsule image) */
  UINT32                      LbaAddr;

} CAPSULE_INFO_CFG_DATA;

#pragma pack()

#endif
